name: Reset Beta Branch


on: [workflow_dispatch]
jobs:
  resetBeta:
    name: Reset Beta Branch
    runs-on: ubuntu-latest
    steps:
      - name: print working directory
        run: |
          pwd
      - name: file listing
        run: ls

