# reset beta branch to master
name: Reset Beta Branch


on: [workflow_dispatch]
jobs:
  resetBeta:
    name: Reset Beta Branch
    runs-on: ubuntu-latest
    # reset beta branch to master
    steps:
      - name: Checkout Beta
        uses: actions/checkout@v3
        with:
          branch: beta
          force: 1
      - run: git reset --hard master
      - run: git push
      - run: git branch
