
name: Reset Beta Branch


on:
  workflow_dispatch
jobs:
  resetBeta:
    name: Reset Beta Branch
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          repository: aphexlog/dog
          ssh-key: ${{secrets.DEPLOY_KEY}}
          ref: beta
      - name: reset branch to master
        run: |
          git branch
          git config user.name github-actions
          git config user.email github-actions@github.com
          git reset --hard origin/master
          git push -f
