name: Reset Beta Branch

on:
  workflow_dispatch
jobs:
  resetBeta:
    name: Reset Beta Branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          ref: master
      - id: commit
        uses: pr-mpt/actions-commit-hash@v2
      - name: Checkout Beta Branch
        uses: actions/checkout@v3
        with:
          ref: beta
      - name: Get Current Branch Name
        run: git branch
      - name: Set Git User
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: reset branch to master
        run: |
          git fetch --all
          git diff beta..master | patch -p1
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: Changes by reset-beta-branch action
          body: Reset beta branch back to head of master ${{ steps.commit.outputs.short }}
          commit-message: resetting beta branch to master
          add-paths: .
          branch: reset-beta
          delete-branch: true
