
name: Reset Beta Branch


on: [workflow_dispatch]
jobs:
  resetBeta:
    name: Reset Beta Branch
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: reset branch to master
        run: |
          git config --global user.name "aaron.west"
          git config --global user.email "aphexlog@gmail.com"
          git checkout beta
          git branch
          git fetch --all
          git reset --hard origin/master
          git push origin/beta
