name: Reset Beta Branch

on:
  workflow_dispatch
jobs:
  resetBeta:
    name: Reset Beta Branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          ref: master
      - id: commit
        uses: pr-mpt/actions-commit-hash@v2
      - name: Checkout Beta Branch
        uses: actions/checkout@v3
        with:
          ref: beta
      - name: Get Current Branch Name
        run: git branch
      - name: Set Git User
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Create Patch Branch
        run: |
          git fetch --all
          git checkout -b reset-beta
      - name: Create Patch, Commit & Push New Branch
          git diff beta..master | patch -p1
          git add .
          git commit -m'resetting beta branch to head of master'
          git push --set-upstream origin reset-beta
      - name: Create PR reset-beta -> beta
          gh pr create -B beta -t "resetting beta branch to head of master" -b "Reset beta branch back to head of master ${{ steps.commit.outputs.short }}"
          
