name: Reset Beta Branch

on:
  workflow_dispatch
jobs:
  resetBeta:
    name: Reset Beta Branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          ref: master
      - id: commit
        uses: pr-mpt/actions-commit-hash@v2
      - name: Checkout Beta Branch
        uses: actions/checkout@v3
        with:
          ref: beta
      - name: Get Current Branch Name
        run: git branch
      - name: Set Git User
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: reset branch to master
        run: |
          git fetch --all
          git reset --hard origin/master
      - name: Sync Branches PR
        uses: monoku/sync-branches-pr@0.0.1
        with:
          SOURCE_BRANCH: master
          TARGET_BRANCH_STARTS_WITH: beta
