name: Reset Beta Branch


on: [workflow_dispatch]
jobs:
  resetBeta:
    name: Reset Beta Branch
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: reset branch
        uses: Joao208/resync-branch@1.5.0
        with:
          BRANCH_NAME: beta
