
name: Reset Beta Branch


on:
  workflow_dispatch
jobs:
  resetBeta:
    name: Reset Beta Branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Beta Branch
        uses: actions/checkout@v3
        with:
          repository: aphexlog/dog
          ref: beta
      - name: Get Current Branch Name
        run: git branch
      - name: Set Git User
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: reset branch to master
        run: |
          git fetch --all
          git reset --hard origin/master
          git push -f
