
name: Reset Beta Branch


on:
  workflow_dispatch
jobs:
  resetBeta:
    name: Reset Beta Branch
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
        ssh-key: ${{ secrets.DEPLOY_KEY}}
        with:
          repository: aphexlog/dog
      - name: reset branch to master
        run: |
          git checkout beta
          git branch
          git reset --hard origin/master
          git push -f
